//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolpack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toolpack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Written by Kurtis (2012)
        ///
        ///This program is made for editing GTA: San Andreas.
        ///Firstly I wanted to make an user-friend program,
        ///although it&apos;s not completly is.
        ///
        ///If you are reading this you might succeded setting
        ///this program to the game, because in other cases
        ///you can&apos;t display this dialog.
        ///
        ///This program is written in Visual C# 2008 Express Edition
        ///using .Net Framework 3.5.
        /// </summary>
        internal static string aboutbox_en {
            get {
                return ResourceManager.GetString("aboutbox_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A programot Kurtis írta (2012)
        ///
        ///A program azért készült, hogy szerkesszük vele a
        ///GTA: San Andreas-t. Elsősorban a legfelhasználó-
        ///barátabb programot próbáltam összerakni, igaz
        ///nem teljessen az.
        ///
        ///Viszont ha ezt olvasod akkor valószínűleg
        ///sikerült beállítanod a játékhoz a programot, mert
        ///egyéb esetben nem tudod ezt a párbeszédpanelt
        ///megjeleníteni.
        ///
        ///Amúgy meg ha jól tudom nem nagyon írt magyar
        ///ember San Andreasra szerkesztő programot, talán
        ///akad 1-2, de inkább modderek jellemzőek ebben
        ///az évben  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aboutbox_hu {
            get {
                return ResourceManager.GetString("aboutbox_hu", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon toolpack {
            get {
                object obj = ResourceManager.GetObject("toolpack", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
